### ISSUE TITLE
indexer-cli includes ANSI color codes in YAML output

### ISSUE THREAD

**Issue by chriswessels** [graphprotocol/indexer#143]
I wanted to backup my rules and cost models, so I did the following:

```sh
$ graph indexer rules get all --output yaml > rules.yaml
$ graph indexer cost get all --output yaml > costmodels.yaml
```

Looking at the contents of these files, they contain ANSI color codes (which confusingly don't display in the terminal when `head`ing the file since it just interprets them).

rules.yaml:
```
[0m- deployment: global[0m
[0m  allocationAmount: "50000.0"[0m
[0m  parallelAllocations: "4"[0m
[0m  maxAllocationPercentage: null[0m
[0m  minSignal: "130.0"[0m
[0m  maxSignal: null[0m
[0m  minStake: null[0m
[0m  minAverageQueryFees: null[0m
[0m  custom: null[0m
[0m  decisionBasis: rules[0m

...
```

costmodels.yaml:
```
[0m- deployment: QmR2uzq3Tt3htYTmefFwJ6eX2aYySY6ZRZkW9LZG39Byrh[0m
[0m  model: default => $CONST + $DAI * $MULT / $DEV;[0m
[0m  variables:[0m
[0m    DAI: "32.9955383622343452"[0m
[0m    DEV: "100"[0m
[0m    MULT: 1[0m
[0m    CONST: "0.5"[0m

...
```

**Comment by hopeyen** [comment]
Hi Chris, ANSI color codes seemed to be added in by the CLI toolkit (`gluegun`). Error messages should be in red if you try out a wrong command, but otherwise the default is white. 
I will go ahead and add some more ~colors~ for printing, and can add a print command that strips ansi if the command is desirable?
