### ISSUE TITLE
Indexer-agent erroneous retries

### ISSUE THREAD

**Issue by fordN** [graphprotocol/indexer#262]
There have been multiple reports of the indexer-agent attempting actions that lead to reverts, erroneously retrying transactions that were successful, etc..   

Much of this behavior looks similar on the surface, but there are a host of related issues that could be the root cause. To aid in reproducing and debugging I've created this issue, so we have a single place to discuss these related issues and share data.

**Comment by cryptovestor21** [comment]
I am in the middle of a horrible experience today trying to set three allocations with the agent:

![image](https://user-images.githubusercontent.com/59484786/125633442-044c9ec3-9f30-49f2-ba1c-97507cbdca4f.png)

I set three rules in graphcli and went away to work on something else and came back to the above (https://etherscan.io/address/0x2177318680D9E9265470903B6D0ddfCc5EDB054C)

Agent logs: 
[agent_allocateTxnSpam.log](https://github.com/graphprotocol/indexer/files/6816560/agent_allocateTxnSpam.log)

I'm looking at something in the region of $500 worth of wasted gas and my Indexing operation is now paralyzed by the pending transactions, unless I want to spend more gas to cancel them.

I'm losing confidence in using the agent in its current state, would be glad to take on any advice on how I can mitigate this and get operational again without breaking the bank, happy to help in any way I can to mitigate the issue.

**Comment by torrential-ops** [comment]
Here are my etherscan txns to add in the mix. I checked my docker log files and there isn't history far enough back to cover the failed transactions. In the future when closing or allocating I will grab the docker logs at that time. Would it be possible to link the code that is managing the transactions from within the indexer-agent?

https://etherscan.io/address/0xA8410aea388F866BB4B6af465c3Aa5b0F7995aB1

**Comment by fordN** [comment]
Thanks @torrential-ops! 

Here's the [transaction management code](https://github.com/graphprotocol/indexer/blob/main/packages/indexer-agent/src/network.ts#L118-L286)

**Comment by fordN** [comment]
The recent indexer components release (v0.17.0) contains improvements in handling situations where the gas price max is being hit to avoid the situation reported by @cryptovestor21 above.  

Keep the cases coming! I'd like to identify and fix all classes of unnecessary retries and failed transactions from the agent.

**Comment by begetan** [comment]
I just found it is trying to open a broken allocation Opyn Gamma Mainnet. I opened cli to close another transaction using Metamask and proxy contract. This tx stuck in pending state. Right after that it start to spam txsns open allocation.

So if it is not expected behavior two possible triggers might be another external transaction or unhealthy deployment.

**Comment by davaymne** [comment]
In case of gas_price increase while closeAllocation tx in pending, it could trigger Agent to generate new tx with higher gas but with the new 'nonce'. 
In case if gas_price continue to grow or remains on the level where tx is still in pending state, Agent keeps creating new tx - trying to close allocation.
That is is by design. 
The only concern is: since TXs are being generated with new nonce - they will not be processed untill tx which has been created earlier with lower gas_price is processed.

**Comment by fordN** [comment]
@davaymne it appears in your case the agent isn't actually using the retry logic, it is failing out of the retry loop before retrying and returning to the decision making process.  It immediately decides to take the same action, so it appears to be a retry.  What is your `transaction-attempts` set to? Can you try setting it to a high number to allow the agent to retry with the same nonce? 

To remedy this case: in the next release the agent will default to a much higher `transaction-attempts` value and introduce a delay if that threshold is hit.

**Comment by begetan** [comment]
We got recently around 20 failed retries for a single failed claim transaction. The repeat interval was less than one minute.

**Comment by aasseman** [comment]
- Indexer agent v0.17.0
- `transaction-attempts` 1 
- `gas-price-max` 100 

While the network gas price was hovering around 100.

Closed and opened 3 allocations, but both times it sent each transaction twice -- 6 txs total when closing, all sent within a second, and same when opening -- with the same gas setting.

![image](https://user-images.githubusercontent.com/33075224/144515647-c2608cff-417f-46ce-b08d-34f1022f02d8.png)

I'd think that a simple solution for all these issues is to stick to a specific nonce for each action, instead of spamming the same function calls with new nonces and having everything fail.

**Comment by begetan** [comment]
**0.17.0** still has this issue
Each time when gas price is close to 100 (we set a max gas price to 100) there are multiply failed transactions.

The root cause is the increasing nonce for the next transaction, while the initial is in the pending state.

The agent should not increase nonce before the final confirmation from the network about fail of the initial transaction. It is according to Ethereum network tx processing: any tx with lower nonce blocks all other transactions, no matter which fee they have.

Another approach is not to change nonce at all, but send a new transaction with the same nonce but +10% higher fee. It will replace old transaction in the mempool and will get mined faster.

**Comment by fordN** [comment]
Closing as updates to transaction management have apparently resolved this issue. I'll reopen if there are any new observations of these erroneous retries.
